Adjust dockerfile, buildspec, etc. to use uv

diff --git a/ci/buildspec.yml b/ci/buildspec.yml
--- a/ci/buildspec.yml
+++ b/ci/buildspec.yml
@@ -17,6 +17,9 @@ phases:
   pre_build:
     commands:
       - |
+        # install uv
+        curl -LsSf https://astral.sh/uv/install.sh | sh
+
         # calculate a hash of the uv lockfile
         # this is used to cache the python environment
         # if the lockfile changes, the cache will be invalidated
@@ -24,9 +27,9 @@ phases:
         PLATFORM=$(uname -m)
         CACHE_FILE_NAME="${UV_HASH}-${PLATFORM}.tar.gz"
 
-        # output where pip is installing stuff to help with debugging
-        PYTHON_INSTALL_LOCATION="/tmp/opt/python/site-packages"
-        echo "Pip install location: ${PYTHON_INSTALL_LOCATION}"
+        # store where uv is caching stuff
+        PYTHON_INSTALL_LOCATION=$(uv cache dir)
+        echo "uv cache location: ${PYTHON_INSTALL_LOCATION}"
 
         # check if the cache exists on S3
         REMOTE_CACHE_LOCATION="s3://${CODEBUILD_CACHE_BUCKET}/atp-uv-cache/${CACHE_FILE_NAME}"
@@ -38,12 +41,10 @@ phases:
         else
           # if the cache does not exist, install dependencies and save the cache to S3
           echo "Cache not found. Installing dependencies."
-          pip install -qq --upgrade pip pipenv
-
-          pipenv sync --system
+          uv sync --frozen
           retval=$?
           if [ ! $retval -eq 0 ]; then
-            (>&2 echo "pipenv sync failed. refusing to continue.")
+            (>&2 echo "uv sync failed. refusing to continue.")
             exit 1
           fi
 
@@ -53,5 +54,5 @@ phases:
         fi
   build:
     commands:
-      - scrapy check
+      - uv scrapy check
       - /bin/bash ci/run_pr_spiders.sh
