Add parquet output alongside GeoJSON (#8798)
* Add parquet output alongside GeoJSON

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* Instead of using a conversion script, write to parquet as an item exporter

* [pre-commit.ci] auto fixes from pre-commit.com hooks

for more information, see https://pre-commit.ci

* Move geopandas dependency to packages instead of dev

* Add pyarrow dependency

* Don't continue the build (or dependency caching) if pipenv sync fails

* Tiny change to trigger CI on new CodeBuild architecture

---------

Co-authored-by: pre-commit-ci[bot] <66853113+pre-commit-ci[bot]@users.noreply.github.com>

diff --git a/ci/buildspec.yml b/ci/buildspec.yml
--- a/ci/buildspec.yml
+++ b/ci/buildspec.yml
@@ -37,7 +37,13 @@ phases:
           # if the cache does not exist, install dependencies and save the cache to S3
           echo "Cache not found. Installing dependencies."
           pip install -qq --upgrade pip pipenv
+
           pipenv sync --system
+          retval=$?
+          if [ ! $retval -eq 0 ]; then
+            (>&2 echo "pipenv sync failed. refusing to continue.")
+            exit 1
+          fi
 
           echo "Caching pipenv environment to $REMOTE_CACHE_LOCATION"
           tar -czf "${CACHE_FILE_NAME}" "${PYTHON_INSTALL_LOCATION}"
@@ -112,11 +118,13 @@ phases:
 
             LOGFILE="${SPIDER_RUN_DIR}/log.txt"
             OUTFILE="${SPIDER_RUN_DIR}/output.geojson"
+            PARQUETFILE="${SPIDER_RUN_DIR}/output.parquet"
             FAILURE_REASON="success"
 
             timeout -k 5s 90s \
             scrapy runspider \
                 -o "file://${OUTFILE}:geojson" \
+                -o "file://${PARQUETFILE}:parquet" \
                 --loglevel=INFO \
                 --logfile="${LOGFILE}" \
                 -s CLOSESPIDER_TIMEOUT=60 \
@@ -173,6 +181,13 @@ phases:
 
                 if grep -q 'Stored geojson feed' $LOGFILE; then
                     echo "${spider} has ${FEATURE_COUNT} features: https://alltheplaces-data.openaddresses.io/map.html?show=${OUTFILE_URL}"
+                fi
+
+                aws s3 cp --only-show-errors ${PARQUETFILE} s3://${BUCKET}/ci/${CODEBUILD_BUILD_ID}/${SPIDER_NAME}/output.parquet
+                retval=$?
+                if [ ! $retval -eq 0 ]; then
+                    (>&2 echo "parquet copy to s3 failed with exit code ${retval}")
+                    exit 1
                 fi
 
                 PR_COMMENT_BODY="${PR_COMMENT_BODY}|[\`$spider\`](https://github.com/alltheplaces/alltheplaces/blob/${GITHUB_SHA}/${spider})|[${FEATURE_COUNT} items](${OUTFILE_URL}) ([Map](https://alltheplaces-data.openaddresses.io/map.html?show=${OUTFILE_URL}))|Resulted in a \`${FAILURE_REASON}\` ([Log](${LOGFILE_URL}))|\\n"
