Add parquet output alongside GeoJSON

diff --git a/ci/buildspec.yml b/ci/buildspec.yml
--- a/ci/buildspec.yml
+++ b/ci/buildspec.yml
@@ -112,6 +112,7 @@ phases:
 
             LOGFILE="${SPIDER_RUN_DIR}/log.txt"
             OUTFILE="${SPIDER_RUN_DIR}/output.geojson"
+            PARQUETFILE="${SPIDER_RUN_DIR}/output.parquet"
             FAILURE_REASON="success"
 
             timeout -k 5s 90s \
@@ -173,6 +174,17 @@ phases:
 
                 if grep -q 'Stored geojson feed' $LOGFILE; then
                     echo "${spider} has ${FEATURE_COUNT} features: https://alltheplaces-data.openaddresses.io/map.html?show=${OUTFILE_URL}"
+                fi
+
+                python ci/convert_to_parquet.py \
+                    --output ${PARQUETFILE} \
+                    ${OUTFILE}
+
+                aws s3 cp --only-show-errors ${PARQUETFILE} s3://${BUCKET}/ci/${CODEBUILD_BUILD_ID}/${SPIDER_NAME}/output.parquet
+                retval=$?
+                if [ ! $retval -eq 0 ]; then
+                    (>&2 echo "parquet copy to s3 failed with exit code ${retval}")
+                    exit 1
                 fi
 
                 PR_COMMENT_BODY="${PR_COMMENT_BODY}|[\`$spider\`](https://github.com/alltheplaces/alltheplaces/blob/${GITHUB_SHA}/${spider})|[${FEATURE_COUNT} items](${OUTFILE_URL}) ([Map](https://alltheplaces-data.openaddresses.io/map.html?show=${OUTFILE_URL}))|Resulted in a \`${FAILURE_REASON}\` ([Log](${LOGFILE_URL}))|\\n"
