Add exit code checks to pr ci flow

diff --git a/.github/workflows/spider-pr.yaml b/.github/workflows/spider-pr.yaml
--- a/.github/workflows/spider-pr.yaml
+++ b/.github/workflows/spider-pr.yaml
@@ -85,8 +85,13 @@ jobs:
             fi
 
             aws s3 cp --only-show-errors ${LOGFILE} s3://${BUCKET}/ci/${GITHUB_RUN_ID}/${SPIDER_NAME}/log.txt
-            LOGFILE_URL="https://data.alltheplaces.xyz/ci/${GITHUB_RUN_ID}/${SPIDER_NAME}/log.txt"
+            retval=$?
+            if [ ! $retval -eq 0 ]; then
+                (>&2 echo "log copy to s3 failed with exit code ${retval}")
+                exit 1
+            fi
 
+            LOGFILE_URL="https://data.alltheplaces.xyz/ci/${GITHUB_RUN_ID}/${SPIDER_NAME}/log.txt"
             echo "${spider} log: ${LOGFILE_URL}"
 
             if [ -f "$OUTFILE" ]; then
@@ -105,6 +110,12 @@ jobs:
                 fi
 
                 aws s3 cp --only-show-errors ${OUTFILE} s3://${BUCKET}/ci/${GITHUB_RUN_ID}/${SPIDER_NAME}/output.geojson
+                retval=$?
+                if [ ! $retval -eq 0 ]; then
+                    (>&2 echo "output copy to s3 failed with exit code ${retval}")
+                    exit 1
+                fi
+
                 OUTFILE_URL="https://data.alltheplaces.xyz/ci/${GITHUB_RUN_ID}/${SPIDER_NAME}/output.geojson"
 
                 if grep -q 'Stored geojson feed' $LOGFILE; then
